-- Copy and paste this into the SQL Editor in your Supabase Dashboard

-- 1. Table Users (Siswa & Guru)
create table if not exists users (
  id text primary key, -- NISN or NIP
  name text not null,
  role text not null check (role in ('student', 'teacher', 'admin')),
  class_name text, -- e.g., '7A', '8B', null for teachers
  pin text default '123456', -- Simple password for protection
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Table Jurnal Salat
create table if not exists journal_sholat (
  id bigint generated by default as identity primary key,
  user_id text references users(id) not null,
  date date not null default current_date,
  subuh boolean default false,
  zuhur boolean default false,
  asar boolean default false,
  magrib boolean default false,
  isya boolean default false,
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, date)
);

-- 3. Table Jurnal Tadarus
create table if not exists journal_tadarus (
  id bigint generated by default as identity primary key,
  user_id text references users(id) not null,
  date date default current_date,
  surah text not null,
  ayat text,
  duration int, -- minutes
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. Table Hafalan
create table if not exists hafalan_progress (
  id bigint generated by default as identity primary key,
  user_id text references users(id) not null,
  category text not null, -- 'juz30', 'iqra', 'bacaan_salat'
  item_name text not null, -- e.g., 'An-Naba', 'Jilid 4', 'Doa Iftitah'
  status text default 'Belum', -- 'Belum', 'Mengulang', 'Lancar', 'Cukup'
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, category, item_name)
);

-- 5. Dummy Data
insert into users (id, name, role, class_name, pin) values
('12345', 'Ahmad Santoso', 'student', '7A', '123'),
('67890', 'Siti Aminah', 'student', '7A', '123'),
('G001', 'Ust. Abdullah', 'teacher', null, 'admin')
on conflict (id) do nothing;
